### ISSUE TITLE
Inquiry Regarding Code Release Date

### ISSUE THREAD

**Issue by 271806** [threedle/3d-paintbrush#1]
Really cool and impressive work, I love it very, very much (especially the CSD part) !
I noticed that the code for this project has not yet been released, and I was wondering if you have an estimated timeline for its availability. Thank you (:

**Comment by BukenyaLukman** [comment]
I have been also waiting for it eagerly. But nothing is popping up

**Comment by ddecatur** [comment]
Code has now been released!
